### ISSUE TITLE
Goodhosts check requires a writable hosts file

### ISSUE THREAD

**Issue by tomjn** [goodhosts/cli#19]
The `check` subcommand requires a writable hosts file, but it doesn't write to the hosts file. I should be able to use the `check` subcommand without needing to use `sudo` or changing the write permissions of the hosts file if it's readable to all users

```
❯ goodhosts check vvv.test
Host file not writable. Try running with elevated privileges.
```

```
❯ sudo goodhosts check vvv.test
vvv.test exists in hosts file
```

**Comment by tomjn** [comment]
Likewise with the `list` `debug` and `backup` subcommands

**Comment by luthermonson** [comment]
super good suggestion, let me see if i can pull that off
