### ISSUE TITLE
goodhosts stalls when the /etc/hosts file has too many entries

### ISSUE THREAD

**Issue by conradolandia** [goodhosts/cli#28]
I block malware sites and ads from the internet using a large hosts file (600.000+ lines), redirecting all these bad hosts to 0.0.0.0. When I try to use goodhosts, it just freezes and whatever process I was on won't go on. If I remove most of the entries form /etc/hosts, the process completes without problems. Is this a bug or expected behavior?

**Comment by luthermonson** [comment]
@conradolandia try v1.1.0 and tell me if you see improvements

https://github.com/goodhosts/cli/releases/tag/v1.1.0

**Comment by conradolandia** [comment]
It works as expected! thank you. Hopefully, developers at vagrant-goodhosts can start using it right away.

**Comment by luthermonson** [comment]
excellent! i will close the issue
