### ISSUE TITLE
Windows maximum aliases per line

### ISSUE THREAD

**Issue by hegemanjr** [goodhosts/cli#34]
As seen here https://superuser.com/questions/932112/is-there-a-maximum-number-of-hostname-aliases-per-line-in-a-windows-hosts-file, there is a maximum of nine aliases per line in the hosts file on Windows.

I am often beyond that maximum of nine aliases in the VVV environments I use, meaning some of my sites don't work without manually splitting the aliases into multiple lines.

Assuming that I'm not the only one running into this, I would like to request a feature that automatically splits the aliases into multiple lines if there are more than nine.

Thanks!

**Comment by luthermonson** [comment]
https://github.com/goodhosts/cli/issues/33

**Comment by luthermonson** [comment]
read through that and confirm. i was under the impression this was configurable and solved but i could be wrong

**Comment by luthermonson** [comment]
@hegemanjr pretty sure this is solved, reopen if you disagree
