### ISSUE TITLE
Q: Maintenance

### ISSUE THREAD

**Issue by tomjn** [goodhosts/cli#5]
Hello!

I'm evaluating using this in conjunction with a vagrant project, and I'm wondering what governance of the org is.

I ask because pretty much every vagrant plugin for modifying hosts files has been abandoned or put in a limbo state, even if people were willing to contribute the original author went AWOL with no way of delegating to a new maintainer.

I see this library is based on one such project, and that there are a few `go` based alternatives that are in similar boats.

I'd really like to avoid having to maintain a legacy ruby vagrant plugin :( I'd rather write a wrapper around a CLI tool like this. Is there an associated project that relies heavily on this that has some maintainer overlap? Or a process for if the current maintainers no longer use/need the project for me or someone else to contribute fixes?

**Comment by luthermonson** [comment]
@tomjn i purposefully moved this to an org to remove the burden from Lex of maintaining it. I then rewrote and updated it to do what i needed that the existing cli lacked and would gladly welcome more contributors in the org if they're willing to put their ring in the hat.

if you would like your vagrant wrapper open sourced and hosted on this org I'm all for adding it and making you the owner so you can contribute to the solution of a single cli tool for all hosts files. let me know if that's something you'd like to do, i'd even help write it up as i literally have that problem myself but lack motivation to starting it.

**Comment by luthermonson** [comment]
@tomjn following up to see if you'd like to discuss more.

**Comment by tomjn** [comment]
Hey that sounds good but let me discuss some more with my colleagues. I’d
done a little research into how to ask for elevated privileges and I’ve a
few options to consider.

Also I had eye surgery 2 days ago so I’ve been taking a little time to rest.

Some notes:

- using sudo in backticks works in vagrant for getting permissions
- there’s a command in Windows that’s similar to sudo but I haven’t
conducted any tests to confirm if this works
- it may be better to build a ruby gem as a library, we have a use case for
embedding a plugin rather than installing it over at VVV
- one option I’d considered was supporting both goodhost and hostctl for
max flexibility. The alternative tools aren’t as recently updated or they
require a runtime such as Node. If that’s the case a good name would be
vagrant-go-hosts otherwise it’d be vagrant-goodhosts
- one of our team has a vagrant hosts manager fork that may cover us in the
meantime, I’ve yet to look into it though

**Comment by luthermonson** [comment]
ah ya rest up and hope for a speedy recovery. whenever you're ready but it seems you've thought about this a bit. you could also embed goodhosts some how, it's only 1.5mb built and is trivial in size in comparison to vagrant images you're already pulling down to get a box booted

**Comment by Mte90** [comment]
I started a vagrant plugin that use this tool https://github.com/Mte90/vagrant-goodhosts but I didn't tested.
It is a fork of https://github.com/cogitatio/vagrant-hostsupdater/ without all the code to edit the hosts file and instead use the cli tool.

So probably need a way to download automatically the binary file for the system.

**Comment by Mte90** [comment]
![Screenshot_20200508_175301](https://user-images.githubusercontent.com/403283/81423546-e09eb800-9154-11ea-9ded-964f8e67032f.png)

Just an example of the output right now, the plugin works as it is.
The only point missing is the `cli` download :-)

I did also a branch of VVV https://github.com/Varying-Vagrant-Vagrants/VVV/tree/vagrant-goodhosts with the support of this plugin.

It is based on the other one so support the same settings but probably there is space for some cleaning as it is now is very simple.

**Comment by Mte90** [comment]
Released the final package with everything https://github.com/Mte90/vagrant-goodhosts/releases/tag/1.0.0-beta looking for some testing.

Right now there is a pr for VVV support for this new plugin https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2148

**Comment by luthermonson** [comment]
@Mte90 that's great! +1 from me

**Comment by luthermonson** [comment]
you guys fine with the repos where they are or do you want a goodhosts/vagrant repo to put this in? no problem to add you as admins to that repo if you want to keep it here.

**Comment by Mte90** [comment]
I can migrate the repo it is not a problem. 
I prefer just to test the plugin now, so I can publish a stable also on rubygems.

**Comment by luthermonson** [comment]
sure, ping me when youre ready. wasn't sure if you needed more from me on it today.

**Comment by Mte90** [comment]
As today no but in the meantime you can add me as admin, so when I am ready I can migrate the repo :-)

**Comment by luthermonson** [comment]
easy peasy, adding now

**Comment by luthermonson** [comment]
you guys good on this question? can i close the issue?

**Comment by tomjn** [comment]
I think we're good to go :) Thanks for being patient and guiding us!

**Comment by luthermonson** [comment]
@tomjn my pleasure, welcome to the goodhosts party
